#[build]
#    command = "npm run build"
#    functions = "functions"
#    publish = "dist"

[build.environment]
    CI = "true"
    # increase the memory allocation for nodejs
    NODE_OPTIONS = "--max_old_space_size=4096"
    # https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-environment
    # If you set the NODE_ENV to production, any devDependencies in your package.json
    # file will not be installed for the build.
    # NODE_ENV = "production"
    NODE_VERSION = "20"

# Allow remote images for Nuxt
# https://docs.netlify.com/image-cdn/overview/#remote-path
[images]
    remote_images = [
        "https://polyguard.com/.*",
        "https://cms.polyguard.com/.*",
        "https://polyguard-cms-staging.bezar.io/.*",
        "https://polyguard-cms.ddev.site/.*",
        "https://polyguard.nyc3.cdn.digitaloceanspaces.com/.*",
        "https://polyguard-staging.nyc3.cdn.digitaloceanspaces.com/.*",
        "https://polyguard-dev.nyc3.cdn.digitaloceanspaces.com/.*",
    ]

