fragment productCategoriesCatalogListingFields on productCategoriesCatalogListing_Entry {
  ...entryInterfaceFields
  doNotShowProductListingPageInBreadcrumbs
  topLevelProductCategory {
    ...entryInterfaceFields
  }

  topLevelProductDivision {
    ...entryInterfaceFields

    ... on productDivisions_default_Entry {
      id
    }
  }

  pageHero {
    ...pageHeroFields
  }

  standardContentBuilder {
    ...entryInterfaceFields
  }
}
