mutation saveCareersslitterassistantSubmission(
  $yourName: Careersslitterassistant_yourName_FormieNameInput
  $emailAddress: String
  $phoneNumber: String
  $message: String
  $resume: FileUploadInput
) {
  save_Careersslitterassistant_Submission(
    phoneNumber: $phoneNumber
    emailAddress: $emailAddress
    resume: [$resume]
    message: $message
    yourName: $yourName
  ) {
    yourName {
      firstName
      lastName
    }
    emailAddress
    phoneNumber
    resume {
      filename
      url
    }
    message
  }
}
