fragment pageSectionsFormosanMapFields on pageSectionsFormosanMap_Entry {
  ...entryInterfaceFields
  primaryText
  timelineEvents {
    ... on blocksTimelineEvents_Entry {
      id
      eventTitle
      eventContent
    }
  }
}
