fragment fieldGroupFrag on Field_Group {
  id
  nestedRows {
    rowFields {
      ...fieldInterfaceFrag
      ... on Field_Dropdown {
        ...fieldDropdownFrag
      }
      ... on Field_Address {
        ...fieldAddressFrag
      }
      ... on Field_Agree {
        ...fieldAgreeFrag
      }
      ... on Field_Phone {
        ...fieldPhoneFrag
      }
    }
  }
}
