fragment pagesLandingPageFields on pagesLandingPage_Entry {
  ...entryInterfaceFields
  doNotShowProductListingPageInBreadcrumbs
  doNotUseDefaultHeader

  pageHero {
    ...pageHeroFields
  }
  standardContentBuilder {
    ...entryInterfaceFields
    ...pageSectionsProductListFields
  }
}
