fragment variantInterfaceFields on VariantInterface {
  __typename
  id
  width
  weight
  uri
  uid
  trashed
  storeId
  stock
  title
  status
  sortOrder
  sku
  siteSettingsId
  siteId
  siteHandle
  shippingCategoryId
  searchScore
  salePriceAsCurrency
  promotionalPriceAsCurrency
  promotionalPrice
  salePrice
  productTypeId
  productTitle
  promotable
  productId
  priceAsCurrency
  price
  minQty
  maxQty
  length
  language
  isDefault
  isAvailable
  height
  hasUnlimitedStock
  freeShipping
  enabled
  dateUpdated
  dateCreated
  availableForPurchase
}
