query GetBlogPost($uri: String) {
  entry(section: "blogPosts", uri: [$uri]) {
    ... on blogDefault_Entry {
      ...blogDefaultEntryFields
    }
    seomatic(asArray: true) {
      ...seomaticFields
    }
  }
}
